plugins {
    id 'java'
    id 'application'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

group = 'net.zytolga'
version = '1.0.0'

application {
    mainClass.set("net.zytolga.Jerry")
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    implementation('ch.qos.logback:logback-classic:1.6.3')
    implementation("net.dv8tion:JDA:6.5.0") {
        // exclude voice modules
        exclude module: 'opus-java' // required for encoding audio into opus, not needed if audio is already provided in opus encoding
        exclude module: 'tink' // required for encrypting and decrypting audio
    }
    implementation 'tools.jackson.core:jackson-databind:3.2.2'

    // TOTP library has vulnerable dependencies. Exclude vulnerable dependencies from the library and add manually with updated versions.
    //noinspection VulnerableLibrariesLocal
    implementation('dev.samstevens.totp:totp:1.7.1') {
        exclude module: 'jcommander'
        exclude module: 'commons-compress'
    }
    implementation 'com.beust:jcommander:1.82'
    implementation('org.apache.commons:commons-compress:1.28.0') {
        exclude module: 'commons-lang'
    }
}

test {
    useJUnitPlatform()
}

shadowJar {
    archiveBaseName.set('jerry')
    archiveClassifier.set('all')

    manifest {
        attributes('Main-Class': application.mainClass.get())
    }

    mergeServiceFiles()
}
